administracion:
  hibernate:
    hbm2ddl:
      auto: none
    dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/BD_ADMINISTRACION?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/BD_ADMINISTRACION?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    initialSize: 1
    minIdle: 2
    maxActive: 5
    maxIdle: 5
