administracion:
  hibernate:
    hbm2ddl:
      auto: none
    dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/BD_ADMINISTRACION?useUnicode=yes&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/BD_ADMINISTRACION?useUnicode=yes&amp;characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Peru123.
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    initialSize: 1
    minIdle: 2
    maxActive: 5
    maxIdle: 5
